# Generated by Django 3.1.6 on 2021-02-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pangres', '0004_auto_20210214_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodeldemo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmodeldemo',
            name='upload_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
